### PR TITLE
Update doc and test to LLVM 12

### PR DESCRIPTION
**Pull request by aquarhead**

### CODE REVIEW

**Comment by aquarhead** [comment]
Will update

**Comment by aquarhead** [comment]
From the API change commit https://gitlab.com/taricorp/llvm-sys.rs/-/commit/62e4353be08255842054a0fb9b0fec3f5af36ed7 it seems there're also additions, do you export them all or just use what you need here?

**Comment by alessandrod** [comment]
I think we should sync all the LLVM_SOURCES, so then we can try to upstream the changes and ideally we won't have to maintain a fork forever

**Comment by aquarhead** [comment]
Added the new files

**Comment by alessandrod** [comment]
Great work, thank you!

**Pull request merged**
